### ISSUE TITLE
LWMA Diff Algoritm

### ISSUE THREAD

**Issue by vitorgamer58** [MarketCashME/marketcash#1]
Bora trocar o algoritmo de ajuste de dificuldade para LWMA, seguindo a tendência da Karbo, Niobio, Blood, Forknote e mais 5 clones da Monero, o objetivo é proteger contra ataques de Hash.
Refer to https://github.com/zawy12/difficulty-algorithms/issues/3, https://github.com/seredat/karbowanec/issues/29, 

 Tem aqui uns exemplos que talvez possam ajudar: https://github.com/wownero/wownero/commit/efe03eb0379d87d521f6fc86cef39ec06c119f41 e https://github.com/niobio-cash/niobio-node-daemon/commit/27b9c1a0c3ae95527f69131a3c21bb81028c385c

**Comment by MarketCashME** [comment]
Obrigado pela indicação Vitor, porém já estamos utilizando este algoritmo.

**Comment by vitorgamer58** [comment]
aí sim meu patrão
